// This file is auto-generated by scripts/generate-versions.ts. Do not edit manually.
export const PACKAGE_NAME = '@prefactor/pi-prefactor-ext' as const;
export const PACKAGE_VERSION = '0.0.1' as const;
