import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { PACKAGE_CONFIGS, ROOT } from './package-config.ts';

type PackageJson = {
  name: string;
  version: string;
};

function buildVersionModuleContents(packageJson: PackageJson): string {
  const quotedName = `'${packageJson.name.replaceAll("'", "\\'")}'`;
  const quotedVersion = `'${packageJson.version.replaceAll("'", "\\'")}'`;

  return `// This file is auto-generated by scripts/generate-versions.ts. Do not edit manually.
export const PACKAGE_NAME = ${quotedName} as const;
export const PACKAGE_VERSION = ${quotedVersion} as const;
`;
}

function getVersionModulePath(packagePath: string): string {
  return join(ROOT, packagePath, 'src', 'version.ts');
}

async function loadVersionModuleContents(packagePath: string): Promise<string> {
  const packageJsonPath = join(ROOT, packagePath, 'package.json');
  const packageJson = JSON.parse(await readFile(packageJsonPath, 'utf8')) as PackageJson;
  return buildVersionModuleContents(packageJson);
}

async function generateVersionModule(packagePath: string): Promise<void> {
  const versionModulePath = getVersionModulePath(packagePath);
  const contents = await loadVersionModuleContents(packagePath);
  await writeFile(versionModulePath, contents);
}

export async function checkVersionModules(): Promise<void> {
  const staleModules: string[] = [];

  for (const pkg of PACKAGE_CONFIGS.filter((entry) => entry.generateVersionModule)) {
    const versionModulePath = getVersionModulePath(pkg.path);
    const expectedContents = await loadVersionModuleContents(pkg.path);
    const existingContents = await readFile(versionModulePath, 'utf8').catch(() => '');

    if (existingContents !== expectedContents) {
      staleModules.push(versionModulePath);
    }
  }

  if (staleModules.length > 0) {
    console.error('SDK version modules are stale. Run `bun run scripts/generate-versions.ts`.');
    for (const modulePath of staleModules) {
      console.error(`- ${modulePath}`);
    }
    process.exit(1);
  }
}

export async function generateVersionModules(): Promise<void> {
  for (const pkg of PACKAGE_CONFIGS.filter((entry) => entry.generateVersionModule)) {
    await generateVersionModule(pkg.path);
  }
}

async function main(args: string[]): Promise<void> {
  if (args.includes('--check')) {
    await checkVersionModules();
    console.log('SDK version modules are up to date.');
    return;
  }

  await generateVersionModules();
}

if (import.meta.main) {
  await main(process.argv.slice(2));
}
