import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const ROOT = import.meta.dir.replace('/scripts', '');
const SDK_PACKAGES = ['core', 'ai', 'langchain'] as const;

type PackageJson = {
  name: string;
  version: string;
};

async function generateVersionModule(packageName: (typeof SDK_PACKAGES)[number]): Promise<void> {
  const packageDir = join(ROOT, 'packages', packageName);
  const packageJsonPath = join(packageDir, 'package.json');
  const versionModulePath = join(packageDir, 'src', 'version.ts');
  const packageJson = JSON.parse(await readFile(packageJsonPath, 'utf8')) as PackageJson;

  const contents = `// This file is auto-generated by scripts/generate-versions.ts. Do not edit manually.
export const PACKAGE_NAME = ${JSON.stringify(packageJson.name)} as const;
export const PACKAGE_VERSION = ${JSON.stringify(packageJson.version)} as const;
`;

  await writeFile(versionModulePath, contents);
}

export async function generateVersionModules(): Promise<void> {
  for (const packageName of SDK_PACKAGES) {
    await generateVersionModule(packageName);
  }
}
